# Generated by Django 5.1.7 on 2025-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('writtensp', models.FloatField()),
                ('actualsp', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
