# Generated by Django 5.1.7 on 2025-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagement', '0002_rename_writtensp_salesdata_cp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='actualsp',
            new_name='sp',
        ),
    ]
